Este es un archivo de prueba, sin actividades =) .

A partir del próximo módulo: M03_variablesydatos vas a tener actividades para realizar.

In [1]:
print('Hola Mundo!')
a = 20
while a > 0:
    
    print(a)
    a -= 1

Hola Mundo!
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1

In [1]:
import pandas as pd 
import matplotlib.pyplot as py 
import seaborn as sns 
import pyodbc as py
import numpy as np

In [2]:
# Conexión a la base de datos
conn = py.connect('Driver={ODBC Driver 17 for SQL Server};'
                      'Server=DESKTOP-4V2EBD8;'
                      'Database=olist;'
                      'Trusted_Connection=yes;')

In [3]:
datos = pd.read_sql_query("select * from tabla_ventas", conn)
datos

C:\Users\david\AppData\Local\Temp\ipykernel_16360\1587178353.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  datos = pd.read_sql_query("select * from tabla_ventas", conn)

,order_id,categoría_calificaciones,calificación_compra,cantidad_productos,gastos,costo_envio,Fecha_estimada_entrega,fecha_entragado_cliente,fecha_respuesta_encuesta,promesa_de_entrega,comentario,titulo_comentario,ciudad
0,00018f77f2f0320c557190d7a144bdd3,Buena experiencia,4.0,1,23990.0,1993.0,2017-05-15,2017-05-12 16:04:24,2017-05-15 11:34:13,1.0,None,None,santa fe do sul
1,00024acbcdf0a6daa1e931b038114c75,Buena experiencia,4.0,1,1299.0,1279.0,2018-08-20,2018-08-14 13:32:39,2018-08-15 16:39:01,1.0,None,None,atibaia
2,00054e8431b9d7675808bcb819fb4a32,Buena experiencia,4.0,1,1990.0,1185.0,2018-01-04,2017-12-18 22:03:38,2017-12-29 02:40:12,1.0,None,None,guararapes
3,0005a1a1728c9d785b8e2b08b904576c,Mala experiencia,1.0,1,14595.0,1165.0,2018-03-29,2018-03-29 18:17:31,2018-04-02 00:52:01,1.0,Na descrição do produto quando fui efetuar a c...,None,santos
4,0005f50442cb953dcd1d21e1fb923495,Buena experiencia,4.0,1,5399.0,1140.0,2018-07-23,2018-07-04 17:28:31,2018-07-05 23:17:04,1.0,None,None,jandira
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fff8286f77788ab8b55b2e5747fa7dd8,Buena experiencia,4.0,1,2499.0,1528.0,2018-07-20,2018-07-06 14:51:40,2018-07-10 16:11:34,1.0,None,None,belo horizonte
99437,fffa82886406ccf10c7b4e35c4ff2788,Buena experiencia,4.0,1,22990.0,4402.0,2018-01-24,2018-01-08 18:23:10,2018-01-11 23:56:38,1.0,None,None,tenente ananias
99438,fffbee3b5462987e66fb49b1c5411df2,Buena experiencia,5.0,1,11985.0,2003.0,2018-07-23,2018-07-05 17:51:08,2018-07-09 10:41:17,1.0,None,None,montes claros
99439,fffc94f6ce00a00581880bf54a75a037,Buena experiencia,5.0,1,29999.0,4341.0,2018-05-18,2018-05-10 22:56:40,2018-05-14 12:53:47,1.0,None,None,sao luis
99440,fffe41c64501cc87c801fd61db3f6244,Buena experiencia,5.0,1,4300.0,1279.0,2018-06-28,2018-06-14 17:56:26,2018-06-17 21:27:09,1.0,None,None,botucatu

In [5]:

suma = datos["calificación_compra"].dropna().sum()
suma

403195.0

In [20]:
calificaciones_1_o_2 = pd.read_sql_query("select order_id, calificación_compra from tabla_ventas where calificación_compra <= 2 ", conn)
calificaciones_1_o_2

C:\Users\david\AppData\Local\Temp\ipykernel_13024\2142333232.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  calificaciones_1_o_2 = pd.read_sql_query("select order_id, calificación_compra from tabla_ventas where calificación_compra <= 2 ", conn)

                               order_id  calificación_compra
0      0005a1a1728c9d785b8e2b08b904576c                    1
1      0030d783f979fbc5981e75613b057344                    1
2      0032d07457ae9c806c79368d7d9ce96b                    1
3      0036757472ece3dde52fd4bfd929c90e                    2
4      003a94f778ef8cfd50247c8c1b582257                    1
...                                 ...                  ...
14478  ffca67b9419980488c476f7f7f7bc070                    2
14479  ffd4172b5df0c16bbd973c196b09bcd9                    1
14480  ffea406a848c8afe4dec22bf6290ba00                    1
14481  ffecd5a79a0084f6a592288c67e3c298                    2
14482  fff0db5573c78c1cb5a2b68a2bbd8d4a                    2

[14483 rows x 2 columns]

In [12]:
calificaciones_uno_o_dos = [[i for i in datos["calificación_compra"] if i <= 2 ], datos["order_id"]]
a = pd.DataFrame(calificaciones_uno_o_dos)

,0,1,2,3,4,5,6,7,8,9,...,99431,99432,99433,99434,99435,99436,99437,99438,99439,99440
0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,...,None,None,None,None,None,None,None,None,None,None
1,00018f77f2f0320c557190d7a144bdd3,00024acbcdf0a6daa1e931b038114c75,00054e8431b9d7675808bcb819fb4a32,0005a1a1728c9d785b8e2b08b904576c,0005f50442cb953dcd1d21e1fb923495,00061f2a7bc09da83e415a52dc8a4af1,000e63d38ae8c00bbcb5a30573b99628,0010b2e5201cc5f1ae7e9c6cc8f5bd00,0011d82c4b53e22e84023405fb467e57,001daeb0eddc45b999bad0801ad9d273,...,ffebd80e3291e811c308365936897efd,ffecd5a79a0084f6a592288c67e3c298,fff0db5573c78c1cb5a2b68a2bbd8d4a,fff1e3e76b816bfe8ef16678cc53c643,fff6b8ca971f8e3ec822e99d0f2d3d21,fff8286f77788ab8b55b2e5747fa7dd8,fffa82886406ccf10c7b4e35c4ff2788,fffbee3b5462987e66fb49b1c5411df2,fffc94f6ce00a00581880bf54a75a037,fffe41c64501cc87c801fd61db3f6244

In [13]:
def categorizar_variable_ordinal(x):
    
    for a in x:
        if a <= 2:
            print("Mala calificación", x) 
        elif a == 3 :
                print("intermedia calificación",x )
        elif a > 3:
                print("Buena calificación",x )
                
    return print(a)

In [17]:
calificaciones_uno_o_dos = [i for i in datos["calificación_compra"] if i <= 2 ]
calificaciones_uno_o_dos

[1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 2.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 2.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 ...]

In [ ]:
int(suma_detractores["calificación_compra"])

TypeError: cannot convert the series to <class 'int'>

In [ ]:
a= 1.618
x = 10
x *= a * a
x

26.179240000000004

In [ ]:

a= [1,2,3,4,5,6,7,8,9,0]
x= [1,3,6,9]

x

[1, 3, 6, 9]

In [ ]:
for i in a:  
    print(i * 10)

10
20
30
40
50
60
70
80
90
0

In [ ]:
numeros = [1,2,3,4,5]
for num in numeros:
    suma= num+1
    print(suma)

2
3
4
5
6

In [ ]:
type(num)

int

In [ ]:

for num in numeros:
    if num == 4:
        print("es cuatro")
        continue
    num =num +1
    print("num ", num)

num  2
num  3
num  4
es cuatro
num  6

In [ ]:

for num in numeros:
    if num == 4:
        print("es cuatro")
        continue
    elif num == 5:
        print("es cinco por la re puta")
        break
    print("num ", num * 2)

TypeError: list indices must be integers or slices, not tuple

In [ ]:
while  x == a:
  if x !=a:
    continue
        print(x)
        x = x * 2

IndentationError: unexpected indent (1399580787.py, line 4)

In [ ]:
for i in a:  
    if i == 5:
        print("Llego a 5")
        break # Sirve para detener la iteración cuando se cumpla la condición del IF, y se detien el código
    print(f" Imprime {i * 10}")

 Imprime 10
 Imprime 20
 Imprime 30
 Imprime 40
Llego a 5

In [ ]:
for i in a:  
    if i == 5:
        print("Llego a 5")
        continue # Sirve para detener la iteración cuando se cumpla la condición del IF, pero continua el código al siguente elemento
    print(f" Imprime {i * 10}")

 Imprime 10
 Imprime 20
 Imprime 30
 Imprime 40
Llego a 5
 Imprime 60
 Imprime 70
 Imprime 80
 Imprime 90
 Imprime 0

In [ ]:
if a < x:
    print(a)
elif a > x :
    print("a es mayor")
elif a == x:
    print("es igual")
else:  "error"

es igual

### Iterador

In [ ]:
text = ["as","asdd","dddas"]
iterasdor = iter(text)
print(next)

<built-in function next>

In [21]:
print(next(iterasdor))

NameError: name 'iterasdor' is not defined

### Funciones

In [23]:
def suma(x):
    x.sum()
    return print(x)

In [27]:
datos

,order_id,categoría_calificaciones,calificación_compra,cantidad_productos,gastos,costo_envio,Fecha_estimada_entrega,fecha_entragado_cliente,fecha_respuesta_encuesta,promesa_de_entrega,comentario,titulo_comentario,ciudad
0,00018f77f2f0320c557190d7a144bdd3,Buena experiencia,4.0,1,23990.0,1993.0,2017-05-15,2017-05-12 16:04:24,2017-05-15 11:34:13,1.0,None,None,santa fe do sul
1,00024acbcdf0a6daa1e931b038114c75,Buena experiencia,4.0,1,1299.0,1279.0,2018-08-20,2018-08-14 13:32:39,2018-08-15 16:39:01,1.0,None,None,atibaia
2,00054e8431b9d7675808bcb819fb4a32,Buena experiencia,4.0,1,1990.0,1185.0,2018-01-04,2017-12-18 22:03:38,2017-12-29 02:40:12,1.0,None,None,guararapes
3,0005a1a1728c9d785b8e2b08b904576c,Mala experiencia,1.0,1,14595.0,1165.0,2018-03-29,2018-03-29 18:17:31,2018-04-02 00:52:01,1.0,Na descrição do produto quando fui efetuar a c...,None,santos
4,0005f50442cb953dcd1d21e1fb923495,Buena experiencia,4.0,1,5399.0,1140.0,2018-07-23,2018-07-04 17:28:31,2018-07-05 23:17:04,1.0,None,None,jandira
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,fff8286f77788ab8b55b2e5747fa7dd8,Buena experiencia,4.0,1,2499.0,1528.0,2018-07-20,2018-07-06 14:51:40,2018-07-10 16:11:34,1.0,None,None,belo horizonte
99437,fffa82886406ccf10c7b4e35c4ff2788,Buena experiencia,4.0,1,22990.0,4402.0,2018-01-24,2018-01-08 18:23:10,2018-01-11 23:56:38,1.0,None,None,tenente ananias
99438,fffbee3b5462987e66fb49b1c5411df2,Buena experiencia,5.0,1,11985.0,2003.0,2018-07-23,2018-07-05 17:51:08,2018-07-09 10:41:17,1.0,None,None,montes claros
99439,fffc94f6ce00a00581880bf54a75a037,Buena experiencia,5.0,1,29999.0,4341.0,2018-05-18,2018-05-10 22:56:40,2018-05-14 12:53:47,1.0,None,None,sao luis
99440,fffe41c64501cc87c801fd61db3f6244,Buena experiencia,5.0,1,4300.0,1279.0,2018-06-28,2018-06-14 17:56:26,2018-06-17 21:27:09,1.0,None,None,botucatu

In [29]:
import pandas as pd
import statsmodels.api as sm

# Supongamos que tienes un DataFrame llamado 'datos'
# con columnas 'ingresos' y 'calificación_compra'

# Calcula el promedio actual de calificación de compra
promedio_actual = datos['calificación_compra'].mean()

# Aumenta el promedio en un 20 %
promedio_aumentado = promedio_actual * 1.2

# Crea un nuevo DataFrame con el promedio aumentado
datos_aumentados = datos.dropna().copy()
datos_aumentados['calificación_compra'] = promedio_aumentado

# Realiza una regresión lineal para predecir los ingresos
X = datos_aumentados['calificación_compra']
y = datos_aumentados['gastos']
X = sm.add_constant(X)  # Agrega una columna constante para el intercepto

model = sm.OLS(y, X).fit()

# Imprime los resultados de la regresión
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 gastos   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Tue, 22 Aug 2023   Prob (F-statistic):                nan
Time:                        17:16:29   Log-Likelihood:            -1.0936e+05
No. Observations:                9489   AIC:                         2.187e+05
Df Residuals:                    9488   BIC:                         2.187e+05
Df Model:                           0
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
calificación_compra  3141.9309     51.292     61.255      0.000    3041.387    3242.475
==============================================================================
Omnibus:                    12925.606   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5293869.582
Skew:                           7.650   Prob(JB):                         0.00
Kurtosis:                     117.697   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.